steps:
  # Install Node dependencies
  - name: 'node:18'
    entrypoint: bash
    args:
      - -c
      - |
        npm install

  # Snyk vulnerability scan
  - name: 'snyk/snyk-cli:docker'
    entrypoint: bash
    args:
      - -c
      - |
        snyk auth $SNYK_TOKEN
        snyk test --all-projects

  # Compliance check
  - name: 'bash'
    entrypoint: bash
    args: ['./check-compliance.sh']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SNYK_TOKEN/versions/latest
      env: SNYK_TOKEN
