steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: bash
    args:
      - -c
      - |
        npm install

  # Step 2: Run SonarQube scanner
  - name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: bash
    args:
      - -c
      - |
        sonar-scanner \
          -Dsonar.projectKey=node-app \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://your-sonarqube.example.com \
          -Dsonar.login=$SONAR_TOKEN

  # Step 3: Package the application
  - name: 'node:18'
    entrypoint: bash
    args:
      - -c
      - |
        tar -czf node-app.tar.gz app.js package.json

  # Step 4: Upload artifact to Artifactory
  - name: 'curlimages/curl:latest'
    entrypoint: bash
    args:
      - -c
      - |
        curl -u "$ARTIFACTORY_USER:$ARTIFACTORY_PASS" \
          -T node-app.tar.gz \
          "https://your-artifactory.example.com/artifactory/libs-release-local/com/demo/node-app/1.0.0/node-app.tar.gz"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/ARTIFACTORY_USER/versions/latest
      env: ARTIFACTORY_USER
    - versionName: projects/$PROJECT_ID/secrets/ARTIFACTORY_PASS/versions/latest
      env: ARTIFACTORY_PASS
    - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/latest
      env: SONAR_TOKEN
