substitutions:
  _SERVICE_NAME: bg-app
  _REGION: us-central1

steps:
  # 1. Build the container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA', '.']

  # 2. Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA']

  # 3. Deploy the Green revision with NO traffic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA
      - --region=$_REGION
      - --platform=managed
      - --no-traffic
      - --allow-unauthenticated

  # 4. Get Green revision URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: get-url
    entrypoint: bash
    args:
      - -c
      - |
        URL=$(gcloud run services describe $_SERVICE_NAME \
          --region=$_REGION --format="value(status.url)")
        echo "GREEN_URL=$URL" >> $BUILD_ENV_FILE

  # 5. Run health check
  - name: 'bash'
    entrypoint: bash
    args:
      - chmod +x ./scripts/health-check.sh
      - ./scripts/health-check.sh
      - "$GREEN_URL"

  # 6. If successful, route 100% traffic to new revision
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - run
      - services
      - update-traffic
      - $_SERVICE_NAME
      - --to-latest
      - --region=$_REGION

timeout: 900s
